CREATE OR REPLACE SEQUENCE KIPI.RAW.seq_ITEMIZED_TR START = 1 INCREMENT = 1 ORDER;

CREATE OR REPLACE TABLE KIPI.RAW.ITEMIZED_TRANSACTIONS_DATA
(
    DETAIL_TRANSACTION_KEY INTEGER DEFAULT KIPI.RAW.seq_ITEMIZED_TR.nextval,
    BANK VARCHAR(10),
    REGION VARCHAR(10),
    STATUS VARCHAR(10),
	FUNDS_CODE VARCHAR(10),
	AMOUNT_VALUE FLOAT,
	ID VARCHAR(10),
	CUSTOMER_REFERENCE VARCHAR(100),
	BANK_REFERENCE VARCHAR(100),
	CURRENCY VARCHAR(10),
	TR_DATE DATE,
	ENTRY_DATE DATE,
	GUESSED_ENTRY_DATE DATE,
	TRANSACTION_REFERENCE VARCHAR(100),
    ACCOUNT_IDENTIFICATION VARCHAR(100),
	TRANSACTION_DETAILS VARCHAR(16777216),
    CREATED_ON TIMESTAMP,
    GUESSED_TRANSACTION_REF VARCHAR(100),
    FILE_NAME VARCHAR(200)
);
